#!/bin/bash

Dealer schedule date and time

0310_Dealer_schedule:05:00:00 AM        Billy Jones
0310_Dealer_schedule:08:00:00 AM        Billy Jones
0310_Dealer_schedule:02:00:00 PM        Billy Jones
0310_Dealer_schedule:08:00:00 PM        Billy Jones
0310_Dealer_schedule:11:00:00 PM        Billy Jones
0312_Dealer_schedule:05:00:00 AM        Billy Jones
0312_Dealer_schedule:08:00:00 AM        Billy jones
0312_Dealer_schedule:02:00:00 PM        Billy Jones
0312_Dealer_schedule:08:00:00 PM        Billy Jones
0312_Dealer_schedule:11:00:00 PM        Billy Jones
0315_Dealer_schedule:05:00:00 AM        Billy Jones
0315_Dealer_schedule:08:00:00 AM        Billy Jones
0315_Dealer_schedule:02:00:00 PM        Billy Jones

player winnings date and time 

0310_win_loss_player_data:05:00:00 AM   -$82,348         Mylie Schmidt
0310_win_loss_player_data:08:00:00 AM   -$97,383         Mylie Schmidt
0310_win_loss_player_data:02:00:00 PM   -$82,348         Mylie Schmidt
0310_win_loss_player_data:08:00:00 PM   -$65,348         Mylie Schmidt
0310_win_loss_player_data:11:00:00 PM   -$88,383         Mylie Schmidt
0312_win_loss_player_data:05:00:00 AM   -$182,300        Mylie Schmidt
0312_win_loss_player_data:08:00:00 AM   -$97,383         Mylie Schmidt
0312_win_loss_player_data:02:00:00 PM   -$82,348         Mylie Schmidt
0312_win_loss_player_data:08:00:00 PM   -$65,792         Mylie Schmidt
0312_win_loss_player_data:11:00:00 PM   -$88,229         Mylie Schmidt
0315_win_loss_player_data:05:00:00 AM   -$82,844         Mylie Schmidt
0315_win_loss_player_data:08:00:00 AM   -$97,001         Mylie Schmidt
0315_win_loss_player_data:02:00:00 PM   -$182,419        Mylie Schmidt



The Dealer named Billy Jones was working the same time and date as the player named Mylie Schmidt in the casino. Billy and Mylie were most likely collaborating when the lucky duck casino lost the money.

